[package]
name = "nannou_isf"
version ="0.1.0"
authors = ["mitchmindtree <mitchell.nordine@gmail.com>"]
edition = "2018"

[dependencies]
hotglsl = "0.2"
isf = { git = "https://github.com/nannou-org/isf", branch = "master" }
nannou = { version ="0.19.0", path = "../nannou", features = ["spirv"] }
thiserror = "1"
threadpool = "1"
walkdir = "2"
