[package]
name = "run_all_examples"
version = "0.1.0"
authors = [
    "mitchmindtree <mitchell.nordine@gmail.com>",
]

[[bin]]
name = "run_all_examples"
path = "main.rs"

[dependencies]
toml = "0.5"

