[workspace]
members = [
    "bevy_nannou",
    "bevy_nannou_draw",
    "bevy_nannou_render",
    "bevy_nannou_wgpu",
    "examples",
    "generative_design",
    "guide/book_tests",
    "nannou",
    "nannou_audio",
    "nannou_core",
    "nannou_egui",
    "nannou_egui_demo_app",
    "nannou_isf",
    "nannou_laser",
    "nannou_mesh",
    "nannou_new",
    "nannou_osc",
    "nannou_package",
    "nannou_wgpu",
    "nature_of_code",
    "scripts/run_all_examples",
    "scripts/set_version",
]

# Required for wgpu v0.10 feature resolution.
resolver = "2"

[workspace.dependencies]
bevy = { git = "https://github.com/bevyengine/bevy", branch = "main", features = ["default"] }