[package]
name = "nannou"
version = "0.10.0"
authors = ["mitchmindtree <mitchell.nordine@gmail.com>"]
description = "A Creative Coding Framework for Rust."
readme = "README.md"
keywords = ["creative", "sketch", "graphics", "audio"]
license = "MIT"
repository = "https://github.com/nannou-org/nannou.git"
homepage = "https://github.com/nannou-org/nannou"
edition = "2018"

[features]
default = ["notosans"]

[dependencies]
approx = "0.1"
cgmath = { version = "0.16", features = ["serde"] }
conrod_core = "0.67"
conrod_winit = "0.67"
conrod_vulkano = "0.67"
daggy = "0.6"
find_folder = "0.3"
image = "0.21"
lyon = "0.14"
noise = "0.5"
notosans = { version = "0.1", optional = true }
palette = "0.4"
pennereq = "0.3"
rand = "0.7"
serde = "1"
serde_derive = "1"
serde_json = "1"
toml = "0.4"
vulkano = "0.14"
vulkano-win = "0.14"
vulkano-shaders = "0.14"
walkdir = "2"
winit = "0.19"

[dev-dependencies]
audrey = "0.2"
nannou_audio = "0.2"
nannou_laser = "0.3"
nannou_osc = "0.1"
shade_runner = "0.2"

[target.'cfg(target_os = "macos")'.dependencies]
moltenvk_deps = "0.1"

# --------------- Nannou Examples
[[example]]
name = "all_functions"
path = "examples/all_functions.rs"
[[example]]
name = "loop_mode"
path = "examples/loop_mode.rs"
[[example]]
name = "multi_window"
path = "examples/multi_window.rs"
[[example]]
name = "named_color_reference"
path = "examples/named_color_reference.rs"
[[example]]
name = "osc_receiver"
path = "examples/osc_receiver.rs"
[[example]]
name = "osc_sender"
path = "examples/osc_sender.rs"
[[example]]
name = "simple_audio"
path = "examples/simple_audio.rs"
[[example]]
name = "simple_audio_file"
path = "examples/simple_audio_file.rs"
[[example]]
name = "simple_draw"
path = "examples/simple_draw.rs"
[[example]]
name = "simple_mesh"
path = "examples/simple_mesh.rs"
[[example]]
name = "simple_polygon"
path = "examples/simple_polygon.rs"
[[example]]
name = "simple_polyline"
path = "examples/simple_polyline.rs"
[[example]]
name = "simple_ui"
path = "examples/simple_ui.rs"
[[example]]
name = "simple_window"
path = "examples/simple_window.rs"
[[example]]
name = "template_app"
path = "examples/template_app.rs"
[[example]]
name = "template_sketch"
path = "examples/template_sketch.rs"

# --------------- Examples Basics
[[example]]
name = "1_nannou_events"
path = "examples/basics/1_nannou_events.rs"
[[example]]
name = "2_variables_window_console"
path = "examples/basics/2_variables_window_console.rs"
[[example]]
name = "3_variable_scope"
path = "examples/basics/3_variable_scope.rs"
[[example]]
name = "4_conditionals"
path = "examples/basics/4_conditionals.rs"
[[example]]
name = "5_loops"
path = "examples/basics/5_loops.rs"
[[example]]
name = "6_functions"
path = "examples/basics/6_functions.rs"
[[example]]
name = "7_modules"
path = "examples/basics/7_modules/7_modules.rs"

# --------------- Vulkan Examples
[[example]]
name = "vk_triangle"
path = "examples/vulkan/vk_triangle.rs"
[[example]]
name = "vk_triangle_raw_frame"
path = "examples/vulkan/vk_triangle_raw_frame.rs"
[[example]]
name = "vk_teapot"
path = "examples/vulkan/vk_teapot.rs"
[[example]]
name = "vk_quad_warp"
path = "examples/vulkan/vk_quad_warp/vk_quad_warp.rs"
[[example]]
name = "vk_teapot_camera"
path = "examples/vulkan/vk_teapot_camera.rs"
[[example]]
name = "vk_image"
path = "examples/vulkan/vk_image.rs"
[[example]]
name = "vk_images"
path = "examples/vulkan/vk_images.rs"
[[example]]
name = "vk_image_sequence"
path = "examples/vulkan/vk_image_sequence.rs"
[[example]]
name = "vk_compute_shader"
path = "examples/vulkan/vk_compute_shader.rs"
[[example]]
name = "vk_shader_include"
path = "examples/vulkan/vk_shader_include/mod.rs"
[[example]]
name = "vk_debug"
path = "examples/vulkan/vk_debug.rs"
[[example]]
name = "vk_hotload"
path = "examples/vulkan/vk_hotload.rs"

# --------------- Generative Design
[[example]]
name = "p_1_0_01"
path = "examples/generative_design/color/p_1_0_01.rs"
[[example]]
name = "p_1_1_1_01"
path = "examples/generative_design/color/p_1_1_1_01.rs"
[[example]]
name = "p_1_1_2_01"
path = "examples/generative_design/color/p_1_1_2_01.rs"
[[example]]
name = "p_1_2_1_01"
path = "examples/generative_design/color/p_1_2_1_01.rs"
[[example]]
name = "p_1_2_3_01"
path = "examples/generative_design/color/p_1_2_3_01.rs"
[[example]]
name = "p_1_2_3_02"
path = "examples/generative_design/color/p_1_2_3_02.rs"
[[example]]
name = "p_1_2_3_03"
path = "examples/generative_design/color/p_1_2_3_03.rs"
# --------------- Shape
[[example]]
name = "p_2_0_01"
path = "examples/generative_design/shape/p_2_0_01.rs"
[[example]]
name = "p_2_0_02"
path = "examples/generative_design/shape/p_2_0_02.rs"
[[example]]
name = "p_2_0_03"
path = "examples/generative_design/shape/p_2_0_03.rs"
[[example]]
name = "p_2_1_1_01"
path = "examples/generative_design/shape/p_2_1_1_01.rs"
[[example]]
name = "p_2_1_1_02"
path = "examples/generative_design/shape/p_2_1_1_02.rs"
[[example]]
name = "p_2_1_1_03"
path = "examples/generative_design/shape/p_2_1_1_03.rs"
[[example]]
name = "p_2_1_2_01"
path = "examples/generative_design/shape/p_2_1_2_01.rs"
[[example]]
name = "p_2_1_2_02"
path = "examples/generative_design/shape/p_2_1_2_02.rs"
[[example]]
name = "p_2_1_2_03"
path = "examples/generative_design/shape/p_2_1_2_03.rs"
[[example]]
name = "p_2_1_2_04"
path = "examples/generative_design/shape/p_2_1_2_04.rs"
# --------------- Random and Noise
[[example]]
name = "m_1_1_01"
path = "examples/generative_design/random_and_noise/m_1_1_01.rs"
[[example]]
name = "m_1_2_01"
path = "examples/generative_design/random_and_noise/m_1_2_01.rs"
[[example]]
name = "m_1_3_01"
path = "examples/generative_design/random_and_noise/m_1_3_01.rs"
# --------------- Oscillation Figures
[[example]]
name = "m_2_1_01"
path = "examples/generative_design/oscillation_figures/m_2_1_01.rs"
[[example]]
name = "m_2_2_01"
path = "examples/generative_design/oscillation_figures/m_2_2_01.rs"
[[example]]
name = "m_2_3_01"
path = "examples/generative_design/oscillation_figures/m_2_3_01.rs"
[[example]]
name = "m_2_3_02"
path = "examples/generative_design/oscillation_figures/m_2_3_02.rs"
[[example]]
name = "m_2_5_01"
path = "examples/generative_design/oscillation_figures/m_2_5_01.rs"
[[example]]
name = "m_2_5_02"
path = "examples/generative_design/oscillation_figures/m_2_5_02.rs"
# --------------- Laser
[[example]]
name = "laser_frame_stream"
path = "examples/laser/laser_frame_stream.rs"
[[example]]
name = "laser_frame_stream_gui"
path = "examples/laser/laser_frame_stream_gui.rs"
[[example]]
name = "laser_raw_stream"
path = "examples/laser/laser_raw_stream.rs"
# --------------- Nature of Code
# --------------- Chapter 1 Vectors
[[example]]
name = "1_1_bouncingball_novectors"
path = "examples/nature_of_code/chp_01_vectors/1_1_bouncingball_novectors.rs"
[[example]]
name = "1_2_bouncingball_vectors_object"
path = "examples/nature_of_code/chp_01_vectors/1_2_bouncingball_vectors_object.rs"
[[example]]
name = "1_2_bouncingball_vectors"
path = "examples/nature_of_code/chp_01_vectors/1_2_bouncingball_vectors.rs"
[[example]]
name = "1_3_vector_subtraction"
path = "examples/nature_of_code/chp_01_vectors/1_3_vector_subtraction.rs"
[[example]]
name = "1_4_vector_multiplication"
path = "examples/nature_of_code/chp_01_vectors/1_4_vector_multiplication.rs"
[[example]]
name = "1_5_vector_magnitude"
path = "examples/nature_of_code/chp_01_vectors/1_5_vector_magnitude.rs"
[[example]]
name = "1_6_vector_normalize"
path = "examples/nature_of_code/chp_01_vectors/1_6_vector_normalize.rs"
[[example]]
name = "1_7_motion101"
path = "examples/nature_of_code/chp_01_vectors/1_7_motion101.rs"
[[example]]
name = "1_8_motion101_acceleration"
path = "examples/nature_of_code/chp_01_vectors/1_8_motion101_acceleration.rs"
[[example]]
name = "1_9_motion101_acceleration"
path = "examples/nature_of_code/chp_01_vectors/1_9_motion101_acceleration.rs"
[[example]]
name = "1_10_motion101_acceleration"
path = "examples/nature_of_code/chp_01_vectors/1_10_motion101_acceleration.rs"
[[example]]
name = "1_11_motion101_acceleration_array"
path = "examples/nature_of_code/chp_01_vectors/1_11_motion101_acceleration_array.rs"
# --------------- Chapter 2 Forces
[[example]]
name = "2_1_forces"
path = "examples/nature_of_code/chp_02_forces/2_1_forces.rs"
[[example]]
name = "2_2_forces_many"
path = "examples/nature_of_code/chp_02_forces/2_2_forces_many.rs"
[[example]]
name = "2_3_forces_many_real_gravity"
path = "examples/nature_of_code/chp_02_forces/2_3_forces_many_real_gravity.rs"
[[example]]
name = "2_4_forces_friction"
path = "examples/nature_of_code/chp_02_forces/2_4_forces_friction.rs"
[[example]]
name = "2_4_forces_no_friction"
path = "examples/nature_of_code/chp_02_forces/2_4_forces_no_friction.rs"
[[example]]
name = "2_5_fluid_resistance"
path = "examples/nature_of_code/chp_02_forces/2_5_fluid_resistance.rs"
[[example]]
name = "2_6_attraction"
path = "examples/nature_of_code/chp_02_forces/2_6_attraction.rs"
[[example]]
name = "2_7_attraction_many"
path = "examples/nature_of_code/chp_02_forces/2_7_attraction_many.rs"
[[example]]
name = "2_8_mutual_attraction"
path = "examples/nature_of_code/chp_02_forces/2_8_mutual_attraction.rs"
[[example]]
name = "2_10_exercise_attract_repel"
path = "examples/nature_of_code/chp_02_forces/2_10_exercise_attract_repel.rs"
[[example]]
name = "2_forces_many_mutual_boundaries"
path = "examples/nature_of_code/chp_02_forces/2_forces_many_mutual_boundaries.rs"
# --------------- Chapter 3 Oscillation
[[example]]
name = "3_01_angular_motion"
path = "examples/nature_of_code/chp_03_oscillation/3_01_angular_motion.rs"
[[example]]
name = "3_02_forces_angular_motion"
path = "examples/nature_of_code/chp_03_oscillation/3_02_forces_angular_motion.rs"
[[example]]
name = "3_04_polar_to_cartesian"
path = "examples/nature_of_code/chp_03_oscillation/3_04_polar_to_cartesian.rs"
[[example]]
name = "3_04_polar_to_cartesian_trail"
path = "examples/nature_of_code/chp_03_oscillation/3_04_polar_to_cartesian_trail.rs"
[[example]]
name = "3_04_exercise_spiral"
path = "examples/nature_of_code/chp_03_oscillation/3_04_exercise_spiral.rs"
[[example]]
name = "3_05_simple_harmonic_motion"
path = "examples/nature_of_code/chp_03_oscillation/3_05_simple_harmonic_motion.rs"
[[example]]
name = "3_06_simple_harmonic_motion"
path = "examples/nature_of_code/chp_03_oscillation/3_06_simple_harmonic_motion.rs"
[[example]]
name = "3_07_oscillating_objects"
path = "examples/nature_of_code/chp_03_oscillation/3_07_oscillating_objects.rs"
[[example]]
name = "3_08_static_wave_lines"
path = "examples/nature_of_code/chp_03_oscillation/3_08_static_wave_lines.rs"
[[example]]
name = "3_09_exercise_additive_wave"
path = "examples/nature_of_code/chp_03_oscillation/3_09_exercise_additive_wave.rs"
[[example]]
name = "3_09_wave_a"
path = "examples/nature_of_code/chp_03_oscillation/3_09_wave_a.rs"
[[example]]
name = "3_09_wave_b"
path = "examples/nature_of_code/chp_03_oscillation/3_09_wave_b.rs"
[[example]]
name = "3_09_wave_c"
path = "examples/nature_of_code/chp_03_oscillation/3_09_wave_c.rs"
[[example]]
name = "3_09_wave"
path = "examples/nature_of_code/chp_03_oscillation/3_09_wave.rs"
[[example]]
name = "3_10_pendulum_example_simplified"
path = "examples/nature_of_code/chp_03_oscillation/3_10_pendulum_example_simplified.rs"
[[example]]
name = "3_10_pendulum_example"
path = "examples/nature_of_code/chp_03_oscillation/3_10_pendulum_example.rs"
[[example]]
name = "3_11_spring"
path = "examples/nature_of_code/chp_03_oscillation/3_11_spring.rs"
[[example]]
name = "3_10_exercise_oop_wave"
path = "examples/nature_of_code/chp_03_oscillation/3_10_exercise_oop_wave.rs"
[[example]]
name = "3_11_exercise_additive_wave"
path = "examples/nature_of_code/chp_03_oscillation/3_11_exercise_additive_wave.rs"
[[example]]
name = "3_16_exercise_springs"
path = "examples/nature_of_code/chp_03_oscillation/3_16_exercise_springs.rs"
[[example]]
name = "3_16_exercise_springs_array"
path = "examples/nature_of_code/chp_03_oscillation/3_16_exercise_springs_array.rs"
[[example]]
name = "3_exercise_spring_sine"
path = "examples/nature_of_code/chp_03_oscillation/3_exercise_spring_sine.rs"
[[example]]
name = "3_extra_oscillating_body"
path = "examples/nature_of_code/chp_03_oscillation/3_extra_oscillating_body.rs"
[[example]]
name = "3_extra_oscillating_up_and_down"
path = "examples/nature_of_code/chp_03_oscillation/3_extra_oscillating_up_and_down.rs"
[[example]]
name = "3_multiple_oscillations"
path = "examples/nature_of_code/chp_03_oscillation/3_multiple_oscillations.rs"
[[example]]
name = "3_oop_wave_particles"
path = "examples/nature_of_code/chp_03_oscillation/3_oop_wave_particles.rs"
# --------------- Chapter 4 Systems
[[example]]
name = "4_01_single_particle"
path = "examples/nature_of_code/chp_04_systems/4_01_single_particle.rs"
[[example]]
name = "4_01_single_particle_trail"
path = "examples/nature_of_code/chp_04_systems/4_01_single_particle_trail.rs"
[[example]]
name = "4_02_vector_particle"
path = "examples/nature_of_code/chp_04_systems/4_02_vector_particle.rs"
[[example]]
name = "4_03_particle_system_type"
path = "examples/nature_of_code/chp_04_systems/4_03_particle_system_type.rs"
[[example]]
name = "4_04_system_of_systems"
path = "examples/nature_of_code/chp_04_systems/4_04_system_of_systems.rs"
[[example]]
name = "4_05_particle_system_inheritance_polymorphism"
path = "examples/nature_of_code/chp_04_systems/4_05_particle_system_inheritance_polymorphism.rs"
[[example]]
name = "4_06_particle_system_forces"
path = "examples/nature_of_code/chp_04_systems/4_06_particle_system_forces.rs"
[[example]]
name = "4_07_particle_system_forces_repeller"
path = "examples/nature_of_code/chp_04_systems/4_07_particle_system_forces_repeller.rs"
[[example]]
name = "4_03_exercise_moving_particle_system"
path = "examples/nature_of_code/chp_04_systems/4_03_exercise_moving_particle_system.rs"
[[example]]
name = "4_06_exercise_shatter"
path = "examples/nature_of_code/chp_04_systems/4_06_exercise_shatter.rs"
[[example]]
name = "4_10_exercise_particle_intersection"
path = "examples/nature_of_code/chp_04_systems/4_10_exercise_particle_intersection.rs"
[[example]]
name = "4_10_exercise_particle_repel"
path = "examples/nature_of_code/chp_04_systems/4_10_exercise_particle_repel.rs"
# --------------- Chapter 6 Agents
[[example]]
name = "6_01_seek"
path = "examples/nature_of_code/chp_06_agents/6_01_seek.rs"
# --------------- Chapter 7 Cellular Automata
[[example]]
name = "7_01_wolfram_ca_figures"
path = "examples/nature_of_code/chp_07_cellular_automata/7_01_wolfram_ca_figures.rs"
[[example]]
name = "7_01_wolfram_ca_simple"
path = "examples/nature_of_code/chp_07_cellular_automata/7_01_wolfram_ca_simple.rs"
[[example]]
name = "7_02_game_of_life_simple"
path = "examples/nature_of_code/chp_07_cellular_automata/7_02_game_of_life_simple.rs"
[[example]]
name = "7_03_game_of_life_oop"
path = "examples/nature_of_code/chp_07_cellular_automata/7_03_game_of_life_oop.rs"
[[example]]
name = "7_04_exercise_wolfram_ca_scrolling"
path = "examples/nature_of_code/chp_07_cellular_automata/7_04_exercise_wolfram_ca_scrolling.rs"
[[example]]
name = "7_game_of_life_wrap_around"
path = "examples/nature_of_code/chp_07_cellular_automata/7_game_of_life_wrap_around.rs"
[[example]]
name = "7_hexagon_cells"
path = "examples/nature_of_code/chp_07_cellular_automata/7_hexagon_cells.rs"
# --------------- Chapter 8 Fractals
[[example]] 
name = "8_1_recursion" 
path = "examples/nature_of_code/chp_08_fractals/8_1_recursion.rs"
[[example]] 
name = "8_2_recursion" 
path = "examples/nature_of_code/chp_08_fractals/8_2_recursion.rs"
[[example]] 
name = "8_3_recursion" 
path = "examples/nature_of_code/chp_08_fractals/8_3_recursion.rs"
[[example]] 
name = "8_4_cantor_set" 
path = "examples/nature_of_code/chp_08_fractals/8_4_cantor_set.rs"
# --------------- Chapter 10 Neural Networks
[[example]] 
name = "10_01_simple_perceptron" 
path = "examples/nature_of_code/chp_10_neural_networks/10_01_simple_perceptron.rs"
[[example]] 
name = "10_02_seeking_neural" 
path = "examples/nature_of_code/chp_10_neural_networks/10_02_seeking_neural.rs"
[[example]] 
name = "10_03_network_viz" 
path = "examples/nature_of_code/chp_10_neural_networks/10_03_network_viz.rs"

# --------------- Offline examples
[[example]]
name = "offline_01"
path = "examples/offline/tree.rs"
