[package]
name = "set_version"
version = "0.1.0"
authors = ["mitchmindtree <mitchell.nordine@gmail.com>"]
description = "A small tool for setting a new version across all nannou crates."
edition = "2018"

[[bin]]
name = "run_all_examples"
path = "main.rs"

[dependencies]
semver = "0.9"
toml_edit = "0.1"
